# azure-pipeline.yaml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: AzureResourceManagerTemplateDeployment@3
    displayName: 'Create Resource Group'
    inputs:
      deploymentScope: 'Resource Group'
      azureResourceManagerConnection: 'Microsoft Partner Network (71815b3c-ac05-4504-8f3f-6d7f27ce722f)'
      subscriptionId: '71815b3c-ac05-4504-8f3f-6d7f27ce722f'
      action: 'Create Or Update Resource Group'
      resourceGroupName: 'resgrp'
      location: 'West US'
      templateLocation: 'Linked artifact'
      csmFile: 'azure-resource-group.json'
      overrideParameters: '-resourceGroupName $(resourceGroupName)'
      deploymentMode: 'Incremental'
